# Copyright (c) OpenMMLab. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Based on MMDeploy's FindTENSORRT.cmake and adapted for MwInfer.

set(TENSORRT_ROOT "" CACHE PATH "Optional TensorRT installation prefix.")
set(TENSORRT_DIR "" CACHE PATH "Optional TensorRT installation prefix.")

if(NOT TENSORRT_DIR AND TENSORRT_ROOT)
  set(TENSORRT_DIR "${TENSORRT_ROOT}")
endif()

if(NOT TENSORRT_DIR AND DEFINED ENV{TENSORRT_DIR})
  set(TENSORRT_DIR "$ENV{TENSORRT_DIR}")
endif()

if(NOT TENSORRT_DIR AND DEFINED ENV{TENSORRT_ROOT})
  set(TENSORRT_DIR "$ENV{TENSORRT_ROOT}")
endif()

set(_TENSORRT_INCLUDE_SUFFIXES include)
set(_TENSORRT_LIBRARY_SUFFIXES lib lib64 lib/x64)

if(CMAKE_LIBRARY_ARCHITECTURE)
  list(APPEND _TENSORRT_INCLUDE_SUFFIXES
       "include/${CMAKE_LIBRARY_ARCHITECTURE}"
       "targets/${CMAKE_LIBRARY_ARCHITECTURE}/include")
  list(APPEND _TENSORRT_LIBRARY_SUFFIXES "lib/${CMAKE_LIBRARY_ARCHITECTURE}"
       "targets/${CMAKE_LIBRARY_ARCHITECTURE}/lib")
endif()

find_path(
  TENSORRT_INCLUDE_DIR
  NAMES NvInfer.h
  HINTS ${TENSORRT_DIR} ${CUDAToolkit_ROOT} ${CUDA_TOOLKIT_ROOT_DIR}
  PATH_SUFFIXES ${_TENSORRT_INCLUDE_SUFFIXES}
  NO_SYSTEM_ENVIRONMENT_PATH)

find_file(
  TENSORRT_VERSION_HEADER
  NAMES NvInferVersion.h
  HINTS ${TENSORRT_DIR} ${CUDAToolkit_ROOT} ${CUDA_TOOLKIT_ROOT_DIR}
  PATH_SUFFIXES ${_TENSORRT_INCLUDE_SUFFIXES}
  NO_SYSTEM_ENVIRONMENT_PATH)

find_library(
  TENSORRT_NVINFER_LIBRARY
  NAMES nvinfer nvinfer_10 nvinfer_9 nvinfer_8
  HINTS ${TENSORRT_DIR} ${CUDAToolkit_ROOT} ${CUDA_TOOLKIT_ROOT_DIR}
  PATH_SUFFIXES ${_TENSORRT_LIBRARY_SUFFIXES}
  NO_SYSTEM_ENVIRONMENT_PATH)

find_library(
  TENSORRT_NVINFER_PLUGIN_LIBRARY
  NAMES nvinfer_plugin nvinfer_plugin_10 nvinfer_plugin_9 nvinfer_plugin_8
  HINTS ${TENSORRT_DIR} ${CUDAToolkit_ROOT} ${CUDA_TOOLKIT_ROOT_DIR}
  PATH_SUFFIXES ${_TENSORRT_LIBRARY_SUFFIXES}
  NO_SYSTEM_ENVIRONMENT_PATH)

if(TENSORRT_VERSION_HEADER)
  file(STRINGS "${TENSORRT_VERSION_HEADER}" _TENSORRT_VERSION_MAJOR_LINE
       REGEX "^#define[ \t]+NV_TENSORRT_MAJOR[ \t]+[0-9]+")
  file(STRINGS "${TENSORRT_VERSION_HEADER}" _TENSORRT_VERSION_MINOR_LINE
       REGEX "^#define[ \t]+NV_TENSORRT_MINOR[ \t]+[0-9]+")
  file(STRINGS "${TENSORRT_VERSION_HEADER}" _TENSORRT_VERSION_PATCH_LINE
       REGEX "^#define[ \t]+NV_TENSORRT_PATCH[ \t]+[0-9]+")

  string(REGEX REPLACE "^#define[ \t]+NV_TENSORRT_MAJOR[ \t]+([0-9]+).*$" "\\1"
                       TensorRT_VERSION_MAJOR "${_TENSORRT_VERSION_MAJOR_LINE}")
  string(REGEX REPLACE "^#define[ \t]+NV_TENSORRT_MINOR[ \t]+([0-9]+).*$" "\\1"
                       TensorRT_VERSION_MINOR "${_TENSORRT_VERSION_MINOR_LINE}")
  string(REGEX REPLACE "^#define[ \t]+NV_TENSORRT_PATCH[ \t]+([0-9]+).*$" "\\1"
                       TensorRT_VERSION_PATCH "${_TENSORRT_VERSION_PATCH_LINE}")

  if(TensorRT_VERSION_MAJOR STREQUAL ""
     OR TensorRT_VERSION_MINOR STREQUAL ""
     OR TensorRT_VERSION_PATCH STREQUAL "")
    message(FATAL_ERROR
            "Could not parse TensorRT version from ${TENSORRT_VERSION_HEADER}.")
  endif()

  set(TensorRT_VERSION
      "${TensorRT_VERSION_MAJOR}.${TensorRT_VERSION_MINOR}.${TensorRT_VERSION_PATCH}")

  if(TensorRT_VERSION_MAJOR EQUAL 8)
    set(TensorRT_API_FAMILY 8)
  elseif(TensorRT_VERSION_MAJOR EQUAL 10)
    set(TensorRT_API_FAMILY 10)
  else()
    message(FATAL_ERROR
            "MwInfer supports TensorRT 8.x and 10.x. Found TensorRT ${TensorRT_VERSION}.")
  endif()
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  TensorRT REQUIRED_VARS TENSORRT_INCLUDE_DIR TENSORRT_VERSION_HEADER
                         TENSORRT_NVINFER_LIBRARY
                         TENSORRT_NVINFER_PLUGIN_LIBRARY
           VERSION_VAR TensorRT_VERSION)

set(_TENSORRT_COMPILE_DEFINITIONS
    "MW_INFER_TENSORRT_VERSION_MAJOR=${TensorRT_VERSION_MAJOR}"
    "MW_INFER_TENSORRT_VERSION_MINOR=${TensorRT_VERSION_MINOR}"
    "MW_INFER_TENSORRT_VERSION_PATCH=${TensorRT_VERSION_PATCH}"
    "MW_INFER_TENSORRT_API_FAMILY=${TensorRT_API_FAMILY}")

if(TensorRT_FOUND AND NOT TARGET TensorRT::nvinfer)
  add_library(TensorRT::nvinfer UNKNOWN IMPORTED)
  set_target_properties(
    TensorRT::nvinfer
    PROPERTIES IMPORTED_LOCATION "${TENSORRT_NVINFER_LIBRARY}"
               INTERFACE_INCLUDE_DIRECTORIES "${TENSORRT_INCLUDE_DIR}"
               INTERFACE_COMPILE_DEFINITIONS "${_TENSORRT_COMPILE_DEFINITIONS}")
endif()

if(TensorRT_FOUND AND NOT TARGET TensorRT::nvinfer_plugin)
  add_library(TensorRT::nvinfer_plugin UNKNOWN IMPORTED)
  set_target_properties(
    TensorRT::nvinfer_plugin
    PROPERTIES IMPORTED_LOCATION "${TENSORRT_NVINFER_PLUGIN_LIBRARY}"
               INTERFACE_INCLUDE_DIRECTORIES "${TENSORRT_INCLUDE_DIR}")
endif()

unset(_TENSORRT_COMPILE_DEFINITIONS)
unset(_TENSORRT_INCLUDE_SUFFIXES)
unset(_TENSORRT_LIBRARY_SUFFIXES)
unset(_TENSORRT_VERSION_MAJOR_LINE)
unset(_TENSORRT_VERSION_MINOR_LINE)
unset(_TENSORRT_VERSION_PATCH_LINE)

mark_as_advanced(TENSORRT_INCLUDE_DIR TENSORRT_NVINFER_LIBRARY
                 TENSORRT_NVINFER_PLUGIN_LIBRARY TENSORRT_VERSION_HEADER)
